In [1]:
import numpy as np

In [2]:
a=np.array([5,6,8])
a

array([5, 6, 8])

In [3]:
a.dtype

dtype('int64')

In [5]:
a=np.array([5,6,8],dtype=float) #you can specify the data type inside the ()

In [6]:
a

array([ 5.,  6.,  8.])

In [7]:
a=np.array([3.4,5,7.7])
a

array([ 3.4,  5. ,  7.7])

In [8]:
a.dtype

dtype('float64')

In [10]:
#specifying the dimensions of the matrix
np.zeros([3,4])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [11]:
np.zeros([3,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
np.arange(10,20,2) #it does not go to 20, 2 is the interval

array([10, 12, 14, 16, 18])

In [17]:
np.linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [18]:
np.pi

3.141592653589793

In [20]:
np.linspace(0,2*np.pi,200)

array([ 0.        ,  0.0315738 ,  0.06314759,  0.09472139,  0.12629518,
        0.15786898,  0.18944277,  0.22101657,  0.25259036,  0.28416416,
        0.31573796,  0.34731175,  0.37888555,  0.41045934,  0.44203314,
        0.47360693,  0.50518073,  0.53675452,  0.56832832,  0.59990211,
        0.63147591,  0.66304971,  0.6946235 ,  0.7261973 ,  0.75777109,
        0.78934489,  0.82091868,  0.85249248,  0.88406627,  0.91564007,
        0.94721387,  0.97878766,  1.01036146,  1.04193525,  1.07350905,
        1.10508284,  1.13665664,  1.16823043,  1.19980423,  1.23137803,
        1.26295182,  1.29452562,  1.32609941,  1.35767321,  1.389247  ,
        1.4208208 ,  1.45239459,  1.48396839,  1.51554218,  1.54711598,
        1.57868978,  1.61026357,  1.64183737,  1.67341116,  1.70498496,
        1.73655875,  1.76813255,  1.79970634,  1.83128014,  1.86285394,
        1.89442773,  1.92600153,  1.95757532,  1.98914912,  2.02072291,
        2.05229671,  2.0838705 ,  2.1154443 ,  2.14701809,  2.17

In [23]:
#reshape the dimensions of the array
np.arange(0,12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
a=np.array([10,20,30,40])
b=np.arange(4)

In [26]:
print(a)
print(b)

[10 20 30 40]
[0 1 2 3]


In [27]:
a-b

array([10, 19, 28, 37])

In [28]:
a+1

array([11, 21, 31, 41])

In [29]:
a**2

array([ 100,  400,  900, 1600])

In [33]:
a+=1 #adding a certain value to the array

In [34]:
print(a)

[11 21 31 41]


In [35]:
#comparing every element in the list to 20: boolean
a<20

array([ True, False, False, False], dtype=bool)

In [40]:
A=np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [42]:
np.array([1,2,3,4]).reshape(2,2) #notice the difference between array and arange

array([[1, 2],
       [3, 4]])

In [45]:
B=np.array([[5,6],[7,8]])
B

array([[5, 6],
       [7, 8]])

In [46]:
A-B

array([[-4, -4],
       [-4, -4]])

In [47]:
A**2

array([[ 1,  4],
       [ 9, 16]])

In [48]:
#A×B: multiply each element by element
A*B

array([[ 5, 12],
       [21, 32]])

In [49]:
#A.B: the first value is the first row multiplies the first column
#1*5+2*7=19
#n×m · m×j=n×j
A.dot(B)

array([[19, 22],
       [43, 50]])

In [59]:
#Creating 12 number between 1 and 100

np.random.seed(100) #setting a seed enables us to produce the same result everytime

b=np.random.randint(1,100,12).reshape(4,3)

array([ 0.21010774,  0.4527399 ,  0.87014264,  0.06368104,  0.62431189,
        0.52334774,  0.56229626,  0.00581719,  0.30742321,  0.95018431,
        0.12665424,  0.07898787])

In [58]:
#Creating random numbers from different distributions
np.random.normal(10,1)
np.random.random(12) #Return random floats in the half-open interval [0.0, 1.0).

8.559228816670247

In [60]:
b.min()

9

In [61]:
b.max()

99

In [62]:
b.sum()

698

In [63]:
#0 is for columns, 1 is for rows
b.sum(axis=0) 

array([207, 254, 237])

In [64]:
b.sum(axis=1) #sum of rows

array([102, 217, 159, 220])

In [72]:
c=np.arange(1,11)

In [68]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
a=c**2

In [70]:
a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [73]:
a[4:6]

array([25, 36])

In [76]:
#Selecting every other element
a[::2] ### a[start:end:step] step by default is 1
#OR

array([ 1,  9, 25, 49, 81])

In [77]:
a[0:10:2]

array([ 1,  9, 25, 49, 81])

In [78]:
a[::-1] # reverse order

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1])

In [79]:
a[::-2] #reverse order with decrements of 2

array([100,  64,  36,  16,   4])

In [80]:
a**(1/2)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [82]:
for i in a:
    print(np.sqrt(i))

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [85]:
b=np.arange(30,50,1).reshape(4,5)

In [88]:
print(b)
print(b[2,3]) #notice python starts from 0

[[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
43


In [90]:
#Nested for loops
#need two for loops to go from left to right & from top to bottom

for i in range(4): 
    #we put rows for loop first because you will fix the row number and change
    #column number
    for j in range(5):
        print(b[i,j]+1)

31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50


In [96]:
b=np.arange(0,100,5).reshape(4,5)

In [97]:
print(b)

[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]


In [99]:
for i in range(4):
    for j in range(5):
        if b[i,j]%5==0:
            if b[i,j]%10!=0:
                print(b[i,j])
            else:
                pass
        else:
            pass

5
15
25
35
45
55
65
75
85
95


In [114]:
for i in range(4):
    for j in range(5):
        if (b[i,j]%10!=0&b[i,j]%5==0):
            print(b[i,j])

5
15
25
35
45
55
65
75
85
95


In [103]:
num_list=np.array([1,2,3])
alpha_list=np.array(['a','b','c'])

In [116]:
for i in num_list:
    print(i)
    for n in alpha_list:
        print(n)

1
a
b
c
2
a
b
c
3
a
b
c


In [117]:
list_of_lists=[['apple','orange','grape'],[0,1,2],[9.9,8.8,7.7]]

In [119]:
for i in list_of_lists:
    for n in i:
        print(n)

apple
orange
grape
0
1
2
9.9
8.8
7.7


In [126]:
d=np.array([[1,2],[3,4]])
e=np.array([[5,6],[7,8]])

In [127]:
print(np.vstack((d,e)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [128]:
print(np.hstack((d,e))) #notice that it is stacking horizontally element by element

[[1 2 5 6]
 [3 4 7 8]]


In [133]:
a=np.arange(12)**2
i=np.array([2,4,2,0])

# Fancy indexing
print(a)
print(a[i])
print(a[[2,4,2,0]])

# Boolean indexing
print(a[a<30])

[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 4 16  4  0]
[ 4 16  4  0]
[ 0  1  4  9 16 25]
